import {
  ArrowRight,
  Award,
  Bank,
  BarChartLine,
  Briefcase,
  Building,
  Buildings,
  Bullseye,
  CalendarCheck,
  CashCoin,
  CashStack,
  ChatDots,
  CheckCircle,
  ChevronRight,
  ClipboardCheck,
  ClipboardData,
  Compass,
  CurrencyExchange,
  DoorOpen,
  DoorClosed,
  Droplet,
  Envelope,
  Eye,
  Facebook,
  Filter,
  GeoAlt,
  GraphUpArrow,
  Heart,
  HouseCheck,
  HouseDoor,
  HouseGear,
  Houses,
  InfoCircle,
  Instagram,
  JournalCheck,
  Key,
  Lightbulb,
  Linkedin,
  List,
  Map,
  PatchCheck,
  People,
  PersonCheck,
  Rulers,
  Search,
  Send,
  ShieldCheck,
  SignpostSplit,
  Sliders2,
  SortDown,
  Speedometer2,
  StarFill,
  Stars,
  Telegram,
  Telephone,
  Tiktok,
  Tools,
  TwitterX,
  Whatsapp,
  XLg,
} from "react-bootstrap-icons";

export const iconMap = {
  arrowRight: ArrowRight,
  award: Award,
  bank: Bank,
  building: Building,
  buildings: Buildings,
  barChart: BarChartLine,
  bed: DoorClosed,
  briefcase: Briefcase,
  bullseye: Bullseye,
  calendarCheck: CalendarCheck,
  cashCoin: CashCoin,
  cashStack: CashStack,
  chatDots: ChatDots,
  checkCircle: CheckCircle,
  chevronRight: ChevronRight,
  clipboardCheck: ClipboardCheck,
  clipboardData: ClipboardData,
  compass: Compass,
  currencyExchange: CurrencyExchange,
  doorOpen: DoorOpen,
  droplet: Droplet,
  envelope: Envelope,
  eye: Eye,
  facebook: Facebook,
  filter: Filter,
  geoAlt: GeoAlt,
  graphUpArrow: GraphUpArrow,
  heart: Heart,
  home: HouseDoor,
  houseCheck: HouseCheck,
  houseDoor: HouseDoor,
  houseGear: HouseGear,
  houses: Houses,
  infoCircle: InfoCircle,
  instagram: Instagram,
  journalCheck: JournalCheck,
  key: Key,
  lightbulb: Lightbulb,
  linkedin: Linkedin,
  list: List,
  map: Map,
  patchCheck: PatchCheck,
  people: People,
  personCheck: PersonCheck,
  rulers: Rulers,
  search: Search,
  send: Send,
  shieldCheck: ShieldCheck,
  signpostSplit: SignpostSplit,
  sliders: Sliders2,
  sortDown: SortDown,
  speedometer: Speedometer2,
  star: StarFill,
  stars: Stars,
  telegram: Telegram,
  telephone: Telephone,
  tiktok: Tiktok,
  tools: Tools,
  twitterX: TwitterX,
  whatsapp: Whatsapp,
  close: XLg,
};

export const getIcon = (iconKey, fallbackKey = "infoCircle") => iconMap[iconKey] || iconMap[fallbackKey] || InfoCircle;
